WIP: create an additional comment section to the video form 163
codetapacademy/codetap.academy pull request #192
Opened 2019-08-28 21:43 UTC by tandaraelena

2019-08-28 21:46 UTC, RadosavAntonio approved these changes
💯 for WIP: #163

2019-08-28 21:50 UTC, BogdanNegura approved these changes
💯

2019-08-28 21:54 UTC, psyhedeliq approved these changes
Awesome! 💯 
Thank you Elena! 🥇

2019-08-28 22:00 UTC, valentin3199 approved these changes

2019-08-29 21:27 UTC, RadosavAntonio approved these changes

2019-08-29 21:42 UTC, valentin3199 approved these changes

2019-08-29 21:57 UTC, psyhedeliq approved these changes
Awesome! 💯

2019-08-30 12:16 UTC, tandaraelena reviewed
https://www.robinwieruch.de/local-storage-react

2019-08-30 20:08 UTC, psyhedeliq approved these changes

2019-08-30 22:01 UTC, BogdanNegura approved these changes
👍

2019-09-01 13:28 UTC, QuintyHH commented on src/component/comment-list/comment-list.component.jsx
> +  console.log(commentList)
Woopsies . What is this doing here :D

2019-09-01 13:52 UTC, marianzburlea requested changes
It's not connected to the database

2019-09-01 13:52 UTC, marianzburlea commented on src/component/comment-list/comment-list.component.jsx
> +  console.log(commentList)
console.log left inside the code

2019-09-01 13:52 UTC, marianzburlea commented on src/component/comment-list/comment-list.component.jsx
> +const CommentList = ({commentList}) => {
spaces for `{commentList}` -> `{ commentList }`

2019-09-01 13:52 UTC, marianzburlea commented on src/component/comment-list/comment-list.component.jsx
> +    '' :
A `No comments` message would look better and more informative.

2019-09-01 13:59 UTC, valentin3199 approved these changes

2019-09-01 22:07 UTC, marianzburlea approved these changes

2019-09-01 22:08 UTC, merged